### ISSUE TITLE
Why copying AUR PKGBUILD without understanding?

### ISSUE THREAD

**Issue by bvaudour** [KaOS-Community-Packages/photoqt#1]
1. It is an update of release, not a rebuild, pkgrel variable has not to be incremented.
2. The added optdepends have nothing to do in the PKGBUILD: they are not part of repos, nor KCP.

Please, read http://kaosx.us/packaging-guide/ and https://wiki.archlinux.org/index.php/PKGBUILD
Don't forget to use pckcp tool before submitting.

**Comment by loopset** [comment]
Sorry, and thank you so much for revert the problem. I have to read more about PKGBUILD's. ANd thanks for the links!
